services:
  - type: web
    name: stockbuddy-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn app:app -b 0.0.0.0:$PORT
    envVars:
      - key: PYTHONPATH
        value: backend
    disk:
      name: db-data
      mountPath: /opt/render/project/src/backend/instance
      sizeGB: 1
